config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :contacts
  
  root 'lookup#search'
  post 'results' => 'lookup#results'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	has_attached_file :avatar, styles: {medium: '300x300>', thumb: '100x100>' },
		default_url: '/images/:style/missing.png'

	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

	belongs_to :user
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :contacts
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
	
		devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :name, :username) }

  	devise_parameter_sanitizer.for(:account_update) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :current_password, :name, :username) }
    
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :business_name, :address, :city, :state, :zip, :phone1, :phone2, :email, :avatar, :user_id)
    end
end

app/controllers/lookup_controller.rb
class LookupController < ApplicationController
  def search
  end

  def results
  	
  	if params[:name]!= nil
	  	name_arr = params[:name].downcase.titleize.split
	  	@results = Contact.where(first_name: name_arr[0], last_name: name_arr[1], user_id: current_user.id)
	  elsif params[:city] != nil
	  	@results = Contact.where(city: params[:city].downcase.titleize, user_id: current_user.id)
	  end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/lookup_helper.rb
module LookupHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :business_name %><br>
    <%= f.text_field :business_name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :phone1 %><br>
    <%= f.text_field :phone1 %>
  </div>
  <div class="field">
    <%= f.label :phone2 %><br>
    <%= f.text_field :phone2 %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class='field'>
    <strong><%= f.label :Upload_Photo%></strong>
    <p></phone2>
    <%= f.file_field :avatar %>
  </div>
  <div>
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<div class='jumbotron'>
  <div class='align-left'>
    <h1>Listing Contacts<small> Clever <abbr title='Mother Fucker'>MF</abbr> human, good job finding this page</small></h1>
  </div>
</div>

<pre>
Apparently this is the style
I should use
For multiple lines of code
Or haikus
</pre>

<table class='table'>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Business name</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Phone1</th>
      <th>Phone2</th>
      <th>Email</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.first_name %></td>
        <td><%= contact.last_name %></td>
        <td><%= contact.business_name %></td>
        <td><%= contact.address %></td>
        <td><%= contact.city %></td>
        <td><%= contact.state %></td>
        <td><%= contact.zip %></td>
        <td><%= contact.phone1 %></td>
        <td><%= contact.phone2 %></td>
        <td><%= contact.email %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', @lookup_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p><%= image_tag @contact.avatar.url(:medium) %></p>

<p>
  <strong>First name:</strong>
  <%= @contact.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @contact.last_name %>
</p>

<p>
  <strong>Business name:</strong>
  <%= @contact.business_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @contact.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @contact.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @contact.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @contact.zip %>
</p>

<p>
  <strong>Phone1:</strong>
  <%= @contact.phone1 %>
</p>

<p>
  <strong>Phone2:</strong>
  <%= @contact.phone2 %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>


<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ContactBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class='container'>
	<div class='pull-right'>
		<% if user_signed_in? %>
			<%= link_to 'Edit Profile', edit_user_registration_path, class: 'btn btn-caution' %>
			<%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
		<% end %>
	</div

	<%= yield %>
</div>

</body>
</html>

app/views/lookup/_form.html.erb
<%= form_tag(results_path) do %>
	<div class='row'>	
		<div class='col-md-4'>
			<div class='form-group'>
				<%= text_field_tag :name, nil, placeholder: 'Search By Name', class: 'form-control' %>
			</div>
		</div>
	</div>

	<div class='form-group'>
		<%= submit_tag 'Search', class: 'btn btn-primary' %>
	</div>

<% end %>	

<%= form_tag(results_path) do %>
	<div class='row'>	
		<div class='col-md-4'>
			<div class='form-group'>
				<%= text_field_tag :city, nil, placeholder: 'Search By City', class: 'form-control' %>
			</div>
		</div>
	</div>

	<div class='form-group'>
		<%= submit_tag 'Search', class: 'btn btn-primary' %>
	</div>

<% end %>	

app/views/lookup/results.html.erb
<h1>Contact Search Results</h1>

<ul>
	<% @results.each do |result| %>
		<li><%= "#{result.first_name} #{result.last_name}" %></li>
	<% end %>
</ul>

app/views/lookup/search.html.erb
	
		<h1>Look Up a Contact</h1>

		<%= render 'form' %>

		<%= link_to 'Add a New Contact', new_contact_path %>